### PR TITLE
Update .travis.yml

### PR DESCRIPTION
**Pull request by kjisoo**
I found that the state of CI would not be right.
Even if the build fails, it shows passing.

The cause was in xcpretty and I modified it.
I refer to [xcpretty](https://github.com/supermarin/xcpretty)
I added a destination for testing.

### CODE REVIEW

**Comment by devxoul** [comment]
@kjisoo Cool! I'll merge this PR when it passes the test. Thanks for your contribution!

**Comment by kjisoo** [comment]
I think the problem depends on Travis.
I have tested it several times same conditions.
It fails one of about 10 times.
Error code 65 issues refer to https://github.com/travis-ci/travis-ci/issues/6675.

Can you restart build from travis?
Or should I add tricks to the script?
I'm not sure what to do.

**Comment by devxoul** [comment]
@kjisoo, I just made a new PR: #18 Could you please review that? Thanks!

**Comment by kjisoo** [comment]
It solved at #18

**Pull request closed without merging**
